version: "3"
volumes:
  dbdata: null
services:
  nginx:
    build:
      context: ./.docker/dev/nginx/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    ports:
      - "8080:80"
  database:
    image: "mysql:5.7"
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"
  redis:
    image: "redis:rc-alpine"
    ports:
      - "63790:6379"
  database_admin:
    image: "phpmyadmin/phpmyadmin:latest"
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    restart: always
    depends_on:
      - database
    links:
      - database:db
    ports:
      - "8181:80"
  app:
    build:
      context: ./.docker/dev/laravel/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    environment:
      - DB_PORT=3306
      - DB_HOST=database
      - REDIS_HOST=redis
