version: "3"
networks:
  laravel: null
services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - mysql
      - php
    networks:
      - laravel
  mysql:
    image: "mysql:5.7.22"
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - "./src:/var/www"
    ports:
      - "9000:9000"
    networks:
      - laravel
  redis:
    image: redis
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel
