version: "3"
volumes:
  dbdata: null
services:
  nginx:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    ports:
      - "8080:80"
  database:
    image: "mysql:5.7"
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33061:3306"
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    environment:
      - DB_PORT=33061
      - DB_HOST=database
