version: "3"
volumes:
  dbdata: null
services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: web.dev.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    ports:
      - "8080:80"
  database:
    image: "mysql:5.7"
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33061:3306"
  redis:
    image: "redis:rc-alpine"
    ports:
      - "63790:6379"
  app:
    build:
      context: ./src/
      dockerfile: app.dev.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    environment:
      - DB_PORT=3306
      - DB_HOST=database
      - REDIS_HOST=redis
